function wprp_toggle(form_name,postID)
{jQuery(form_name).slideToggle(400);return false;}
function wprp_report(form,a)
{var post_ID=form.post.value;var reportas=form.report_as.value;var nonce=form._wpnonce.value;var _post_url=form._post_url.value;jQuery('#wprp_report_link_'+post_ID).hide();jQuery('#wprpform'+post_ID).hide();jQuery('#wprp_message_'+post_ID).fadeIn(100);jQuery('#wprp_message_'+post_ID).html('<i class="fa fa-spinner fa-pulse fa-3x fa-fw"></i> Veuillez patienter un instant, s\'il vous plaît.....');jQuery.post('/signaler'+a+'.php',{postID:post_ID,report_as:reportas,do_ajax_report:"true",wpnonce:nonce,post_url:_post_url},function(data){jQuery('#wprp_message_'+post_ID).html(data);});return false;}
$.createElement=function(a){return jQuery(document.createElement(a))};var loader={url:siteurl+"images/load.gif",replace:function(a){if(typeof a=="string")
a=$("#"+a);else
a.jQuery||(a=$(a));var b=(a.height()-16)/2;if(b<0)
b=0;a.html('<i class="fa fa-spinner fa-pulse fa-3x fa-fw"></i>')},insert:function(a){if(typeof a=="string")
a=$("#"+a);var b=a.next();b.size()>0&&b.hasClass("loader")?b.show():$.createElement("i").attr("class","fa fa-spinner fa-pulse fa-3x fa-fw").addClass("loader").insertAfter(a);a.get(0).nodeName.toLowerCase()=="input"&&a.attr("disabled",true)},remove:function(a){if(typeof a=="string")
a=$("#"+a);var b=a.next();b.size()>0&&b.hasClass("loader")&&b.hide();a.get(0).nodeName.toLowerCase()=="input"&&a.attr("disabled",false)}},error={insert:function(a,b,c){if(typeof b=="string")
b=$("#"+b);if(c==undefined)
c=[];if(c.after){if(b.next().size()>0&&(b.next().hasClass("error")||b.next().hasClass("error_green")))
var d=b.next()}else if(b.prev().size()>0&&(b.prev().hasClass("error")||b.prev().hasClass("error_green")))
d=b.prev();if(d==undefined){d=$.createElement("div");c.after?d.insertAfter(b):d.insertBefore(b)}
d.attr("class",c.error==false?"alert-success":"error");d.text(a);d.hide();d.slideDown(250);c.error==false&&c.hide&&d.delay(1E3*c.hide).slideUp(250)}};var comments={file_id:0,page:1,comments:null,comments_type:null,form:null,button:null,spam_actions:function(a){var b=a.find(".text:first");b.hide();a.find(".report:first").hide();a.mouseenter(function(){b.is(":hidden")&&b.slideDown()});a.mouseleave(function(){b.is(":visible")&&b.slideUp()})},load:function(a){loader.replace(this.comments);this.comments.load("/comment.php?a=comments&ajax=1&f="+this.file_id+"&t="+this.comments_type+"&p="+a,null,function(){comments.attach()})},submit:function(){loader.insert(this.button);$.post("/comment.php?a=submit_comment&ajax=1&t="+this.comments_type+"&f="+this.file_id,this.form.serializeArray(),function(a){error.insert(a.message,comments.form,{error:a.error});if(a.error)
loader.remove(comments.button);else{comments.form.slideUp();a=$.createElement("div").addClass("comment").html('<p><span class="user">'+a.user+'</span> <span class="date">('+a.date+')</span></p><p class="text">'+a.comment+"</p>");var b=comments.comments.children("div:first-child");b.size()>0?b.before(a):comments.comments.append(a)}},"json")},report:function(a){a=a.closest(".comment");a.addClass("spam");comments.spam_actions(a);$.getJSON("/comment.php?a=report_comment&ajax=1&id="+a.attr("id"))},page_click:function(){comments.page+=$(this).hasClass("next")?1:-1;comments.load(comments.page);return false},attach:function(){this.comments.children("div.arrow_nav").find(".next, .previous").click(this.page_click);this.comments.find(".report").click(function(){comments.report($(this))});this.comments.find(".spam").each(function(){comments.spam_actions($(this))})},init:function(a,b){this.file_id=a;this.comments_type=b;this.comments=$("#comments");this.attach();this.form=$("#dle-comments-form");if(this.form.size()>0){this.button=this.form.find("input:submit");this.form.submit(function(){comments.submit();return false});var b=$("#comment_verification_field");b.size()>0&&$("#comment").focusin(function(){if(b.is(":hidden")){b.show();image_verification.attach("comment_verification_field")}})}}};